modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="admin_mod"
version="1.0.0"
displayName="Admin Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Willito, MCreator"

[[dependencies.admin_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




