modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="admin_mod"
version="0.2.1"
displayName="Admin mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Luis64_gamer, MCreator"
description='''
Adds tools for server administrators
'''

[[dependencies.admin_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




